spec:
  template:
    spec:
      containers:
      - name: heapster
        resources:
          requests:
            cpu: "200m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
