apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: kuard
spec:
  replicas: 3
  template:
   metadata:
     labels:
       app: kuard
       version: "2"
   spec:
     containers:
       - name: kuard
         image: "gcr.io/kuar-demo/kuard-amd64:2"
         resources:
           requests:
             cpu: "100m"
             memory: "32Mi"
           limits:
             cpu: "200m"
             memory: "64Mi"
